repos:
  - repo: local
    
    hooks:
      - id: black
        name: black 
        entry: black
        language: system
        types: [python]
        exclude: ^.*\b(migrations)\b.*$

  - repo: local
    
    hooks:
      - id: isort
        name: isort  
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]

  - repo: local
    
    hooks:
      - id: flake8
        name: flake8  
        entry: flake8
        language: system
        types: [python]
      