# Generated by Django 5.1.7 on 2025-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="division",
            field=models.CharField(
                choices=[
                    ("programmers", "Программисты"),
                    ("testers", "Тестировщики"),
                    ("designers", "Дизайнеры"),
                    ("developers", "Разработчики"),
                ],
                default="developers",
                max_length=20,
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="notification",
            field=models.JSONField(
                blank=True, default={}, null=True, verbose_name="Уведомление"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="number_phone",
            field=models.CharField(
                default="00000000000",
                max_length=20,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="position",
            field=models.CharField(
                choices=[
                    ("tech_lead", "Тех_лид"),
                    ("team_lead", "Тим_лид"),
                    ("senior", "Сеньор"),
                    ("middle", "Мидл"),
                    ("junior", "Джун"),
                ],
                default="junior",
                max_length=20,
                verbose_name="Должность",
            ),
        ),
    ]
