# Generated by Django 5.1.7 on 2025-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_users_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="number_phone",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "code",
                    models.CharField(max_length=4, verbose_name="Код подтверждения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
            ],
            options={
                "verbose_name": "Код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
                "indexes": [
                    models.Index(
                        fields=["number_phone", "created_at"],
                        name="accounts_ve_number__175e4e_idx",
                    )
                ],
            },
        ),
    ]
