# Generated by Django 5.2 on 2025-04-27 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["status"], name="api_board_status_6930f6_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority", "date_completion"],
                name="api_task_priorit_ee8719_idx",
            ),
        ),
    ]
