# Generated by Django 5.1.7 on 2025-03-12 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_board_description_alter_additionaltask_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("block", "Block"),
                            ("relates_to", "Relates To"),
                            ("duplicates", "Duplicates"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_task",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relations",
                        to="api.task",
                    ),
                ),
                (
                    "to_task",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relations",
                        to="api.task",
                    ),
                ),
            ],
        ),
    ]
