# Generated by Django 5.1.7 on 2025-03-13 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_taskrelation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.project",
                verbose_name="Проект",
            ),
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="users",
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="users",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
